### ISSUE TITLE
About using infonce with kinetics

### ISSUE THREAD

**Issue by caicj15** [TengdaHan/CoCLR#17]
Have you tried wot evaluate the result of  infonce pretrianed with kinetics? My results show no obvious improvement.

**Comment by JiaxinZhuang** [comment]
Hi ~ Which dataset you choose to evaluate  ? UCF101 or HMDB51 ?

**Comment by caicj15** [comment]
> Hi ~ Which dataset you choose to evaluate ? UCF101 or HMDB51 ?

ucf

**Comment by TengdaHan** [comment]
> Have you tried wot evaluate the result of infonce pretrianed with kinetics? My results show no obvious improvement.

Hi, may I know "No obvious improvement" between which two settings? InfoNCE-pretrained weights vs. randomly-initialized weights?

**Comment by caicj15** [comment]
> > Have you tried wot evaluate the result of infonce pretrianed with kinetics? My results show no obvious improvement.
> 
> Hi, may I know "No obvious improvement" between which two settings? InfoNCE-pretrained weights vs. randomly-initialized weights?

I have tried to pretrain with ucf itself (setting 1) and kinetics (setting 2) respectively, and perform linear evaluation on ucf. I find that linear evaluation results with setting 1 and setting 2 have similar accuracy

**Comment by caicj15** [comment]
> > Have you tried wot evaluate the result of infonce pretrianed with kinetics? My results show no obvious improvement.
> 
> Hi, may I know "No obvious improvement" between which two settings? InfoNCE-pretrained weights vs. randomly-initialized weights?

I only perform infonce pretraining

**Comment by TengdaHan** [comment]
In terms of InfoNCE pretraining:
we find pretrained with K400 still performs (on linear probe) slightly better than pretrained with UCF101, but we also notice the difference is not as big as we expected. 
Intuitively, pretraining with larger data (K400) should give a stronger representation on linear probe. 
I think pretraining with InfoNCE-K400 didn't get better results is because (1) we use S3D backbone, which has limited capacity (2) we cannot afford to pretrain long enough. 
[Researchers from google](https://arxiv.org/pdf/2008.03800.pdf) pretrained an infoNCE-based model with big backbone and for many epochs, it has great linear probe performance (their Table10) -- which (I think) could never be achieved by pretraining the same thing on small dataset like UCF101.
